# If you are not sure what all these fields mean, please refer our documentation here:
# https://evalai.readthedocs.io/en/latest/configuration.html
title: Subtle Differences Recognition Challenge
short_description: Subtle Differences Recognition Challenge Among Visually Similar Objects
description: templates/description.html
evaluation_details: templates/evaluation_details.html
terms_and_conditions: templates/terms_and_conditions.html
image: logo2.jpg
submission_guidelines: templates/submission_guidelines.html
leaderboard_description: Leadership board consists of 2 tasks (captioning and classification), which will be evaluated separately.
evaluation_script: evaluation_script.zip
remote_evaluation: False
is_docker_based: False
start_date: 2024-06-07 00:00:00
end_date: 2024-07-07 23:59:59
published: False

leaderboard:
  - id: 1
    schema:
      {
        "labels": ["Accuracy"],
        "default_order_by": "Accuracy",
        "metadata": {
          "Accuracy": {
            "sort_ascending": True,
            "description": "Accuracy for the difference image selection task.",
          }
        }
      }

  - id: 2
    schema:
      {
        "labels": ["BLEU-4", "CIDEr", "GPT-4", "Total"],
        "default_order_by": "Total",
        "metadata": {
          "BLEU-4": {
            "sort_ascending": True,
            "description": "Similarity between generated and reference captions",
          },
          "CIDEr": {
            "sort_ascending": True,
            "description": "Similarity between generated and reference captions",
          },
          "GPT-4": {
            "sort_ascending": True,
            "description": "Meaning similarity over sentence structures",
          },
        }
      }

challenge_phases:
  - id: 1
    name: Difference Image Selection Task
    description: templates/challenge_phase_1_description.html
    leaderboard_public: True
    is_public: True
    is_submission_public: True
    start_date: 2024-06-07 00:00:00
    end_date: 2024-07-07 23:59:59
    test_annotation_file: annotations/class_renamed_test_annotations.json
    codename: dif
    max_submissions_per_day: 5
    max_submissions_per_month: 50
    max_submissions: 50
    default_submission_meta_attributes:
      - name: method_name
        is_visible: True
        required: True
      - name: method_description
        required: True
        is_visible: True
      - name: project_url
        is_visible: True
      - name: publication_url
        is_visible: True
    submission_meta_attributes:
      - name: Authors
        description: Authors of the method
        type: text
        required: False
    is_restricted_to_select_one_submission: False
    is_partial_submission_evaluation_enabled: False
    allowed_submission_file_types: ".json"
  - id: 2
    name: Conditional Difference Captioning Task
    description: templates/challenge_phase_2_description.html
    leaderboard_public: True
    is_public: True
    is_submission_public: True
    start_date: 2024-06-07 00:00:00
    end_date: 2024-07-07 23:59:59
    test_annotation_file: annotations/capt_renamed_test_annotations.json
    codename: cond
    max_submissions_per_day: 5
    max_submissions_per_month: 50
    max_submissions: 50
    default_submission_meta_attributes:
      - name: method_name
        is_visible: True
      - name: method_description
        is_visible: True
      - name: project_url
        is_visible: True
      - name: publication_url
        is_visible: True
    submission_meta_attributes:
      - name: TextAttribute
        description: Sample
        type: text
      - name: SingleOptionAttribute
        description: Sample
        type: radio
        options: ["A", "B", "C"]
      - name: MultipleChoiceAttribute
        description: Sample
        type: checkbox
        options: ["alpha", "beta", "gamma"]
      - name: TrueFalseField
        description: Sample
        type: boolean
    is_restricted_to_select_one_submission: False
    is_partial_submission_evaluation_enabled: False

dataset_splits:
  - id: 1
    name: Train Split
    codename: train_split
  - id: 3
    name: Test Split
    codename: test_split
  - id: 2
    name: Validation Split
    codename: val_split

challenge_phase_splits:
  - challenge_phase_id: 1
    leaderboard_id: 1
    dataset_split_id: 2
    visibility: 2
    leaderboard_decimal_precision: 2
    is_leaderboard_order_descending: True
  - challenge_phase_id: 1
    leaderboard_id: 1
    dataset_split_id: 3
    visibility: 1
    leaderboard_decimal_precision: 2
    is_leaderboard_order_descending: True
  - challenge_phase_id: 2
    leaderboard_id: 2
    dataset_split_id: 1
    visibility: 2
    leaderboard_decimal_precision: 2
    is_leaderboard_order_descending: True
  - challenge_phase_id: 2
    leaderboard_id: 2
    dataset_split_id: 2
    visibility: 2
    leaderboard_decimal_precision: 2
    is_leaderboard_order_descending: True
  - challenge_phase_id: 2
    leaderboard_id: 2
    dataset_split_id: 3
    visibility: 1
    leaderboard_decimal_precision: 2
    is_leaderboard_order_descending: True
